### ISSUE TITLE
Unable to use on windows 10 machine

### ISSUE THREAD

**Issue by mateors** [svr4/couchbase-lite-cgo#1]
can you show me a step by step process how i can use your libarary to work with my golang project?
After build couchbase-lite-C i have got CouchbaseLiteC.dll libaray along with CouchbaseLiteC.exp, CouchbaseLiteC.lib, CouchbaseLiteCStatic.lib now how can i start with this libaray and embed couchbase lite database with my project?

![image](https://user-images.githubusercontent.com/17635146/76391875-9c807880-639a-11ea-82c7-e1c13365425c.png)

**Comment by svr4** [comment]
Hey @mateors, if you check the README for the project you should have a step by step walk-through needed to execute a basic example with the project. Things you should take note of:

* The built CouchbaseLiteC libraries commit should match the one supported for the project to ensure best compatibility.
* The name of the built library should be changed to libCouchbaseLiteC, with the same extension.
* Be mindful of using the same versions of the tools that I did. I will eventually update everything to their latest versions.

Thanks for your patience.
