### ISSUE TITLE
Unable to build according to your instruction 

### ISSUE THREAD

**Issue by mateors** [svr4/couchbase-lite-cgo#2]
i get the following error after executing : go build command

E:\GOLANG\src\cc>go build
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingwex
/usr/lib/gcc/x86_64-pc-msys/9.3.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lmingw32
collect2: error: ld returned 1 exit status

i thin something wrong with the gcc right?

![image](https://user-images.githubusercontent.com/17635146/96006052-e6649c00-0e5e-11eb-8bc2-178759a12027.png)

**Comment by mateors** [comment]
i fix the above issue re installing mingw-w64-install.exe

i am using go version go1.14.4 windows/amd64
gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0

but now getting  following error:

c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:\Users\mostain\AppData\Local\Temp\go-link-074146123\000002.o: In function `_cgo_a95104e16469_C2func_FLValue_AsArray':
/c/Users/mostain/AppData/Local/Temp/go-build239310378/b035/cgo-gcc-prolog:53: undefined reference to `__errno'
/c/Users/mostain/AppData/Local/Temp/go-build239310378/b035/cgo-gcc-prolog:55: undefined reference to `__errno'
collect2.exe: error: ld returned 1 exit status

could you please help me out?

![image](https://user-images.githubusercontent.com/17635146/96011269-853fc700-0e64-11eb-8e4e-1e9bb889b194.png)

**Comment by mateors** [comment]
I have fix my issue by myself.
If anyone need help please share him my article published on github

https://github.com/mateors/tutorial/blob/main/couchbase-lite-go-version.md

**Comment by svr4** [comment]
Glad to see you were able to fix your issue and published a very thorough article regarding your usage and experience on Windows. Stay safe.
